//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marcom_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi_souvenir_item
    {
        public int id { get; set; }
        public int m_souvenir_id { get; set; }
        public Nullable<long> qty { get; set; }
        public Nullable<long> qty_settlement { get; set; }
        public string note { get; set; }
        public bool is_delete { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public int t_souvenir_id { get; set; }
    }
}
